from pathlib import Path

path = Path('src/total_gateway/regenerative_provider.py')
text = path.read_text(encoding='utf-8')
old = '''            self._store.complete_effect(result)\n        recovered = self._store.recover_regenerative_execution(\n'''
new = '''            dispatched = next((\n                event for event in reversed(self._store.list_execution_events(\n                    identity.request_id, run_id=identity.run_id, generation=identity.generation\n                ))\n                if event.effect_id == record.claim.effect_id\n                and event.event_type == \"step.dispatched\"\n            ), None)\n            self._store.complete_effect(result)\n            if dispatched is None or not dispatched.logical_effect_id or not dispatched.attempt_id or not dispatched.step_id:\n                raise StoreCorruptionError(\"started effect has no canonical dispatch event for crash recovery\")\n            self._store.append_execution_event(\n                event_key=f\"step.ambiguous:{dispatched.step_id}:{dispatched.attempt_id}:restart\",\n                request_id=identity.request_id, run_id=identity.run_id,\n                generation=identity.generation, epoch_index=dispatched.epoch_index,\n                event_type=\"step.ambiguous\", created_at_ms=now_ms,\n                payload={\n                    \"effect_state\": \"AMBIGUOUS\",\n                    \"reason\": \"process_restart_after_dispatch\",\n                    \"result_sha256\": result.result_sha256,\n                },\n                logical_effect_id=dispatched.logical_effect_id,\n                attempt_id=dispatched.attempt_id, step_id=dispatched.step_id,\n                effect_id=record.claim.effect_id, causal_parent_event_id=dispatched.event_id,\n            )\n        recovered = self._store.recover_regenerative_execution(\n'''
if text.count(old) != 1:
    raise SystemExit(f'recovery anchor count={text.count(old)}')
path.write_text(text.replace(old, new, 1), encoding='utf-8', newline='\n')
