"""Rebuild every source-controlled backend overlay with the release interpreter.

The Windows backend is frozen with CPython 3.12 and then receives a readable
source overlay.  Sourceless mirrors in ``frozen_modules`` and
``legacy_pyz_modules`` must therefore be regenerated by that exact interpreter;
shipping stale bytecode from a developer machine is forbidden.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import py_compile
import sys
import tempfile


OMNI_MODULES = (
    ("tool_contracts.py", "omni_body_skill/tool_contracts.pyc"),
    ("tools/delivery_kernel.py", "omni_body_skill/tools/delivery_kernel.pyc"),
    ("tools/skill_router.py", "omni_body_skill/tools/skill_router.pyc"),
    ("tools/ppt_design.py", "omni_body_skill/tools/ppt_design.pyc"),
    ("tools/omni_body_tool.py", "omni_body_skill/tools/omni_body_tool.pyc"),
)
OVERLAY_MODULES = (
    "v3/execution_kernel/orchestrator.py",
    "v3/execution_kernel/tool_scheduler.py",
    "tiangong_life/permissions.py",
)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _compile_atomic(source: Path, destination: Path, *, dfile: str) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=destination.name + ".",
        suffix=".tmp",
        dir=destination.parent,
    )
    os.close(descriptor)
    temporary = Path(temporary_name)
    try:
        py_compile.compile(
            str(source),
            cfile=str(temporary),
            dfile=dfile,
            doraise=True,
            invalidation_mode=py_compile.PycInvalidationMode.UNCHECKED_HASH,
        )
        with temporary.open("r+b") as stream:
            os.fsync(stream.fileno())
        os.replace(temporary, destination)
    finally:
        temporary.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--workspace", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    if sys.version_info[:2] != (3, 12):
        raise RuntimeError(f"Windows frozen overlays require CPython 3.12, got {sys.version}")

    workspace = args.workspace.resolve(strict=True)
    internal = workspace / "app" / "backend" / "tiangong-backend" / "_internal"
    omni_source = internal / "omni_body_skill"
    readable_omni = workspace / "readable-python-source" / "omni_body_skill"
    frozen = internal / "frozen_modules"
    legacy = internal / "legacy_pyz_modules"
    records: list[dict[str, object]] = []

    for source_relative, output_relative in OMNI_MODULES:
        source = omni_source / source_relative
        readable = readable_omni / source_relative
        if source.read_bytes() != readable.read_bytes():
            raise RuntimeError(f"source/readable mirror drift: {source_relative}")
        outputs = (frozen / output_relative, legacy / output_relative)
        for output in outputs:
            _compile_atomic(
                source,
                output,
                dfile=output_relative.replace(".pyc", ".py"),
            )
        if _sha256(outputs[0]) != _sha256(outputs[1]):
            raise RuntimeError(f"frozen/legacy bytecode drift: {output_relative}")
        records.append(
            {
                "module": output_relative,
                "bytes": outputs[0].stat().st_size,
                "sha256": _sha256(outputs[0]),
            }
        )

    for source_relative in OVERLAY_MODULES:
        frozen_source = frozen / source_relative
        legacy_source = legacy / source_relative
        if frozen_source.read_bytes() != legacy_source.read_bytes():
            raise RuntimeError(f"frozen/legacy source drift: {source_relative}")
        output_relative = source_relative + "c"
        outputs = (frozen / output_relative, legacy / output_relative)
        for output in outputs:
            _compile_atomic(frozen_source, output, dfile=source_relative)
        if _sha256(outputs[0]) != _sha256(outputs[1]):
            raise RuntimeError(f"frozen/legacy bytecode drift: {output_relative}")
        records.append(
            {
                "module": output_relative,
                "bytes": outputs[0].stat().st_size,
                "sha256": _sha256(outputs[0]),
            }
        )

    print(
        json.dumps(
            {
                "ok": True,
                "python": f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}",
                "modules": records,
            },
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
