#!/usr/bin/env python3
"""Atomically refresh the source-mode single-process release authority.

Source startup must never trust a checked-in manifest that describes the old
7174/7175/7176 topology.  The manifest is rebuilt from the current source tree
before Electron starts and copied to the source/staging locations that may be
inspected by tooling.  Production manifests remain generated by the release
pipeline and are not touched here.
"""
from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path


def _atomic_write(path: Path, payload: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_symlink() or path.parent.is_symlink():
        raise RuntimeError(f"unsafe source release target: {path}")
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=str(path.parent),
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    import sys

    sys.path.insert(0, str(root / "src"))
    from total_gateway.release_manifest import generate_release_manifest, release_manifest_bytes

    manifest = generate_release_manifest(root)
    payload = release_manifest_bytes(manifest)
    targets = (
        root / "app" / "release" / "release-manifest.json",
        root / "app" / "release-manifest.json",
        root / "app" / "resources" / "release" / "release-manifest.json",
    )
    for target in targets:
        _atomic_write(target, payload)
    print(
        json.dumps(
            {
                "ok": True,
                "release_manifest_sha256": manifest.release_manifest_sha256,
                "component_manifest_sha256": manifest.component_manifest.manifest_sha256,
                "targets": [str(item.relative_to(root)) for item in targets],
            },
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
